export const SET_CURRENT_USER = "SET_CURRENT_USER";

export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const USER_LOADING = "USER_LOADING";

export const GET_ERRORS = "GET_ERRORS";
export const CLEAR_ERRORS = "CLEAR_ERRORS";


export const GET_FOLDER_CONTENT = "GET_FOLDER_CONTENT";
export const CLEAR_ITEM = "CLEAR_ITEM";